name: Trigger API Test Workflow

on:
  deployment_status:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    # Trigger API workflow only if deployment status is success
    if: github.event.deployment_status.state == 'success'
    steps:
      # Trigger Workflow in another repository if the deployment status is Completed
      - name: Trigger Workflow in Another Repository
        run: |

          # Set the required variables
          repo_owner="hoa-pham82" 
          repo_name="api_integration"  
          event_type="trigger-workflow" 

          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.FINE_GRAINED_PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
          -d "{\"event_type\": \"$event_type\"}"
